### ISSUE TITLE
Still a thing?

### ISSUE THREAD

**Issue by KennyGoers** [MrEngineer13/FloatingLabelLayout#2]
Hello,

With the recent updates to Android 5.1 Contacts app, this library could become quite useful! Are you still moving it forward? I've found some oddities when dynamically creating repeating layouts with duplicate IDs and that it tries to retain even when it is disabled in the EditText. These of course are feature requests, but wanted to know if you planned on moving this forward or if there were different design thoughts in Material Design

Thanks!

**Comment by MrEngineer13** [comment]
Kenny,

Sorry but as you may have guessed this library is no longer maintained. There are just too many other Floating Label libraries out there.

Thanks.

**Comment by KennyGoers** [comment]
Yeah, I stumbled over yours first and dug in, then I found others...
